### PR TITLE
Don't echo the MAVEN_PROJECTBASEDIR

### PR DESCRIPTION
**Pull request by kutzi**
This breaks scripts depending on the Maven output

### CODE REVIEW

**Comment by eiden** [comment]
I also ran into this issue as well when trying to do 
`./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive`

Please consider removing the echo

**Comment by kutzi** [comment]
ping

**Comment by Gengar003** [comment]
Related issue: #52

**Comment by mosabua** [comment]
We will take the echo by default out for the next release.

**Comment by mosabua** [comment]
This is now implemented and released

**Pull request closed without merging**
