### PR TITLE
Make artifact compatible with older Java and fix stale maven-wrapper.jar bundled with .tar.gz distribution

### PR DESCRIPTION
**Pull request by mches**
Makes it possible to use Maven Wrapper with Maven 3.2.x on Java 6 among other combinations

### CODE REVIEW

**Comment by mosabua** [comment]
Implemented some of these fixes or newer now. We do not want to support Java 1.6 at this stage anymore so I did not pull that in. Takari stuff is Java 1.7+ n general.

**Comment by mosabua** [comment]
All of this will be release as 0.2.0 soon.

**Comment by mches** [comment]
@mosabua Thanks for the updates. I try to avoid all but Java 8 myself, but I think supporting Java 5 and 6 for just the Maven Wrapper will help those able to use Maven 3, which is not end-of-life, but stuck on building with or striving to maintain strict compatibility with Java 5 or 6 for whatever reason, however hopeless that sounds. For instance, [Byte Buddy](https://github.com/raphw/byte-buddy) aims to maintain strict Java 6 compatibility, while also building with Java 7 and 8. The source of this project is already compatible with source level 1.5, so is there any reason to cruelly cut off support for those projects? Maintaining a fork of this project and centrally publishing separate artifacts to achieve that end could be a real pain.

**Comment by mosabua** [comment]
If you send another PR based on current master I can create another release, but I wont be testing it on Java 5, 6, or 7 ...

**Comment by mches** [comment]
@mosabua That's a good compromise. Please see PR #45. Thank you!

**Pull request closed without merging**
