### PR TITLE
Use Apple-recommended strategy for locating JAVA_HOME.

### PR DESCRIPTION
**Pull request by ksperling**
This works correctly with both Oracle and Apple JDKs.
See https://developer.apple.com/library/mac/qa/qa1170/_index.html

### CODE REVIEW

**Comment by ksperling** [comment]
Is anybody still maintaining this repository?

**Comment by mosabua** [comment]
Yes... let me try to get to testing and  merging this in the next days.

**Comment by mosabua** [comment]
I tested this and it works nicely. Could you @ksperling  sign a Takari CLA and email it to team@takari.io

http://takari.io/support/TakariCLA.pdf

I can then proceed with the merge and work towards a new wrapper/maven plugin release.

fyi @jvanzyl

**Comment by metyl** [comment]
@ksperling Will You sign Takari CLA to merge this PR?

**Comment by ksperling** [comment]
Sorry for the slow reply, will send the CLA through tomorrow.

**Comment by metyl** [comment]
@ksperling Thx for replay, can You rework the PR, there are some conflicts with whitespaces.
@mosabua will You proceed this PR?

**Comment by ksperling** [comment]
I've emailed the CLA and update the PR

**Comment by jvanzyl** [comment]
CLA received. All good.

> On Sep 27, 2016, at 9:43 PM, Karsten Sperling notifications@github.com wrote:
> 
> I've emailed the CLA and update the PR
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

Thanks,

Jason

---

Jason van Zyl
Founder, Takari and Apache Maven
http://twitter.com/jvanzyl

## http://twitter.com/takari_io

**Comment by metyl** [comment]
So can we merge this PR? @mosabua @jvanzyl

**Comment by ksperling** [comment]
bump?

**Comment by mosabua** [comment]
I am merging this .. might want to cut a new release soon @metyl @jvanzyl

**Pull request merged**
