### PR TITLE
Upgrade Maven from v3.5.2 to v3.5.3

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Ref:
  - https://maven.apache.org/ref/3.5.3/
  - https://maven.apache.org/docs/3.5.3/release-notes.html
  - https://maven.apache.org/download.cgi

### CODE REVIEW

**Comment by mosabua** [comment]
Since 3.5.3 was released with some minor problems I was going to wait until 3.5.4 .. but maybe its worth rev'ing now after all.

**Comment by PeterDaveHello** [comment]
It'll be great if it can be updated directly here, but I can still upgrade it locally on each machine. Please let me know if you want me to revise this PR when v3.5.4 released, thanks!

**Pull request closed without merging**
