### PR TITLE
Align Un*x and Windows scripts to both use MAVEN_CONFIG consistently

### PR DESCRIPTION
**Pull request by dsyer**
Tested on Ubuntu 14.04 and Windows 7 64bit.

Fixes gh-3

### CODE REVIEW

**Comment by dsyer** [comment]
N.B. most of this file has been copied from https://github.com/apache/maven/blob/master/apache-maven/src/bin/mvn (which also has the same bugs)

**Review by bshannon — COMMENTED** [review]
This fix needs to be pushed upstream to the "mvn" command.

**Comment by awittha** [comment]
This usage pattern is a limitation of shell scripts.

Applying this change will re-introduce the bug described in PR #13 .

**Comment by bshannon** [comment]
The better fix is not to use MAVEN_CMD_LINE_ARGS in the actual command invocation, but to use:

$MAVEN_CONFIG "$@"

Yes, the quoting problem makes MAVEN_CMD_LINE_ARGS less useful, but at least the value of $MAVEN_CONFIG could be passed to the command.  (Although quoting whitespace in MAVEN_CONFIG is still a problem.)

**Pull request merged**
